---

- name: add repositories for php-fpm
  apt_repository:
    repo: "{{ item.value.repo }}"
    state: present
  with_dict: "{{ php_fpm.repos }}"

- name: install php packages
  apt:
    name: "{{ php_fpm.packages }}"
    state: latest
    update_cache: yes
  notify: restart php-fpm

- name: install php user packages
  apt:
    name: "{{ php_conf.packages }}"
    state: latest
    update_cache: yes
  notify: restart php-fpm
  when: php_conf.packages is defined
