---
- name: add repositories for php-fpm
  yum_repository:
    name: "{{ item.value.name }}"
    baseurl: "{{ item.value.baseurl }}"
    description: Repo managed by Ansible
    gpgcheck: no
  with_dict: "{{ php_fpm.repos }}"

- name: install php packages
  yum:
    name: "{{ php_fpm.packages }}"
    state: latest
  notify: restart php-fpm

- name: install php packages
  yum:
    name: "{{ php_conf.packages }}"
    state: latest
  notify: restart php-fpm
  when: php_conf.packages is defined
